# Generated by Django 4.2.4 on 2023-10-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_pdf_downvotes_pdf_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='topic',
            field=models.TextField(default='default_topic_value'),
        ),
    ]
